version: 1.0.0
description: Routing information for UE traffic

# Format as a map with SUPI as keys
ueRoutingInfo:
  imsi-208930000000003:  # UE sur gNB1 - profil standard
    AN: gNB1
    PathList:
      - DestinationIP: 0.0.0.0
        DestinationPort: ""
        UPF: 
          - UPF-Edge1
          - UPF-Agg1
          - UPF-Core

  imsi-208930000000004:  # UE sur gNB2 - profil URLLC
    AN: gNB2
    PathList:
      - DestinationIP: 0.0.0.0
        DestinationPort: ""
        UPF: 
          - UPF-Edge2
          - UPF-Agg2
          - UPF-Core

  imsi-208930000000005:  # UE sur gNB1 - accès MEC local
    AN: gNB1
    PathList:
      - DestinationIP: 10.80.0.0
        DestinationPort: ""
        UPF: 
          - UPF-Edge1
          - UPF-Agg1
      - DestinationIP: 0.0.0.0
        DestinationPort: ""
        UPF: 
          - UPF-Edge1
          - UPF-Agg1
          - UPF-Core

  imsi-208930000000006:  # UE sur gNB2 - accès IMS
    AN: gNB2
    PathList:
      - DestinationIP: 10.91.0.0
        DestinationPort: ""
        UPF: 
          - UPF-Edge2
          - UPF-Agg2
      - DestinationIP: 0.0.0.0
        DestinationPort: ""
        UPF: 
          - UPF-Edge2
          - UPF-Agg2
          - UPF-Core