info:
  version: 1.0.7
  description: Routing information for UE in URLLC multi-UPF chaining

ueRoutingInfo:
  InternetUsers:
    members:
      - imsi-208930000000001
      - imsi-208930000007487
    topology:
      - A: gNB1
        B: UPF-Edge1
      - A: UPF-Edge1
        B: UPF-Core
    specificPath:
      - dest: 10.100.0.0/16
        path: [UPF-Edge1, UPF-Core]

  URLLCUsers:
    members:
      - imsi-208930000007486
    topology:
      - A: gNB1
        B: UPF-Edge1
      - A: UPF-Edge1
        B: UPF-Agg2
      - A: UPF-Agg2
        B: UPF-Core
    specificPath:
      - dest: 10.101.0.0/16
        path: [UPF-Edge1, UPF-Agg2, UPF-Core]

  MECUsers:
    members:
      - imsi-208930000007485
    topology:
      - A: gNB1
        B: UPF-Edge1
      - A: UPF-Edge1
        B: UPF-Agg1
    specificPath:
      - dest: 10.80.0.0/16
        path: [UPF-Edge1, UPF-Agg1]
      - dest: 10.62.0.0/16
        path: [UPF-Edge1]

routeProfile:
  URLLC:
    forwardingPolicyID: 1
  MEC:
    forwardingPolicyID: 2

pfdDataForApp:
  - applicationId: edge
    pfds:
      - pfdID: pfd1
        flowDescriptions:
          - permit out ip from 10.62.0.0/16 8080 to any