version: 1.0.3
description: UPF-Agg2 initial local configuration

pfcp:
  addr: 172.31.0.32  # Adresse dans le réseau d'agrégation
  nodeID: 172.31.0.32
  retransTimeout: 1s
  maxRetrans: 3

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: 172.31.0.32  # Interface vers UPF-Core
      type: N9
      name: n9_core
    - addr: 172.32.0.32  # Interface vers UPF-Edge
      type: N9
      name: n9_edge

dnnList:
  - dnn: urllc
    cidr: 10.90.0.0/16
  - dnn: ims
    cidr: 10.91.0.0/16

logger:
  enable: true
  level: info
  reportCaller: false