version: 1.0.3
description: UPF-Edge1 initial local configuration

pfcp:
  addr: 172.32.0.33  # Adresse dans le réseau edge
  nodeID: 172.32.0.33
  retransTimeout: 1s
  maxRetrans: 3

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: 172.32.0.33  # Interface vers les gNB
      type: N3
      name: n3
    - addr: 172.32.0.33  # Interface vers UPF-Agg
      type: N9
      name: n9

dnnList:
  - dnn: internet
    cidr: 10.60.0.0/16
  - dnn: urllc
    cidr: 10.61.0.0/16
  - dnn: mec
    cidr: 10.62.0.0/16
  - dnn: ims
    cidr: 10.63.0.0/16

logger:
  enable: true
  level: info
  reportCaller: false